context:
  version: "0.9.2"

package:
  name: azure-pipelines-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/azure-pipelines-language-server/-/azure-pipelines-language-server-${{ version }}.tgz
  sha256: 144bab396bebfa3a3da143c5f039af0b384e115c136e1a0bf8dd15c02a0c6e5c

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "azure-pipelines-language-server 2>&1 | grep -q 'Connection input stream is not set.'"

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A language server for Azure Pipelines YAML
  homepage: https://github.com/microsoft/azure-pipelines-language-server
  repository: https://github.com/microsoft/azure-pipelines-language-server

extra:
  recipe-maintainers:
    - danielnachun
