context:
  version: 0.8.0

package:
  name: azure-pipelines-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/azure-pipelines-language-server/-/azure-pipelines-language-server-${{ version }}.tgz
  sha256: 7e938544c7389795e8dc51c2f4b7d085f2e894e8903faaacce4a7ce2d5e412cd

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "azure-pipelines-language-server 2>&1 | grep -q 'Connection input stream is not set.'"

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A language server for Azure Pipelines YAML
  homepage: https://github.com/microsoft/azure-pipelines-language-server
  repository: https://github.com/microsoft/azure-pipelines-language-server

extra:
  recipe-maintainers:
    - danielnachun
