context:
  version: "0.9.1"

package:
  name: azure-pipelines-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/azure-pipelines-language-server/-/azure-pipelines-language-server-${{ version }}.tgz
  sha256: a0726c5ce93de8cef7c2aa0ea713826c5c2b2074a4c538d50b4025014d5dd1a9

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "azure-pipelines-language-server 2>&1 | grep -q 'Connection input stream is not set.'"

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A language server for Azure Pipelines YAML
  homepage: https://github.com/microsoft/azure-pipelines-language-server
  repository: https://github.com/microsoft/azure-pipelines-language-server

extra:
  recipe-maintainers:
    - danielnachun
