context:
  version: "0.9.0"

package:
  name: azure-pipelines-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/azure-pipelines-language-server/-/azure-pipelines-language-server-${{ version }}.tgz
  sha256: bb67fa7926c2a5b2731dd3e10aceb4f03fd27b9bc16904c9bbf3af0db1e47084

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "azure-pipelines-language-server 2>&1 | grep -q 'Connection input stream is not set.'"

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A language server for Azure Pipelines YAML
  homepage: https://github.com/microsoft/azure-pipelines-language-server
  repository: https://github.com/microsoft/azure-pipelines-language-server

extra:
  recipe-maintainers:
    - danielnachun
